version: '3.1'

services:
  dbDevelopment:
    container_name: dbDevelopment
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - 5432:5432
#    volumes:
#      - ./.pgdata:/var/lib/postgresql/data
  dbTest:
    container_name: dbTest
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - 5433:5432