version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
  backend:
    container_name: backend
    image: ftcs/djcloud:backend
    restart: on-failure
    environment:
      ENVIRONMENT: test
      TEST_TYPE: e2e
      FRONTEND_DOMAIN: http://localhost:3000
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
    container_name: frontend
    image: ftcs/djcloud:frontend
    restart: on-failure
    environment:
      REACT_APP_API_ENDPOINT: http://localhost:8000/api
    ports:
      - 3000:3000
    depends_on:
      - backend
#  cypress:
#    image: "cypress/included:10.4.0"
#    depends_on:
#      - frontend
#    environment:
#      CYPRESS_BASE_URL: http://frontend:3000
#    working_dir: /e2e
#    volumes:
#      - ./:/e2e
