version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
  backend:
    container_name: backend
    image: ftcs/djcloud:backend
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
    container_name: frontend
    image: ftcs/djcloud:frontend
    restart: on-failure
    ports:
      - 3000:3000
    depends_on:
      - backend
