### Create a new user
POST http://localhost:8000/auth/signup
content-type: application/json

{
  "email": "test2@email.com",
  "password": "Qwerty123"
}

### Sign in as an existing user
POST http://localhost:8000/auth/signin
content-type: application/json

{
  "email": "test@email.com",
  "password": "Qwerty123"
}

### Get the currently signed in user
GET http://localhost:8000/auth/whoami

### Sign out
POST http://localhost:8000/auth/signout
