name: ci-process
on:
  pull_request:
    branches:
      - master
jobs:
  unit-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: backend
        run: yarn install

      - name: Unit test
        working-directory: backend
        run: yarn run unit-test

  integration-test:
    runs-on: ubuntu-20.04
    env:
      NODE_ENV: ${{ secrets.NODE_ENV }}
      COOKIE_KEY: ${{ secrets.COOKIE_KEY }}
      COOKIE_SESSION_NAME: ${{ secrets.COOKIE_SESSION_NAME }}
      SALT: ${{ secrets.SALT }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      DO_BUCKET_NAME: ${{ secrets.DO_BUCKET_NAME }}
      DO_ACCESS_KEY: ${{ secrets.DO_ACCESS_KEY }}
      DO_SECRET_KEY: ${{ secrets.DO_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Build the Postgres stack
        working-directory: backend
        run: yarn run docker:run

      - name: Install dependencies
        working-directory: backend
        run: yarn install

      - name: Integration test
        working-directory: backend
        run: yarn run test:integration
