name: ci-process
on:
  push:
    branches:
      - develop
jobs:
  unit-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: cd backend && npm install

      - name: Unit test
        run: cd backend && npm run unit-test

  integration-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ci
          POSTGRES_USER: ci
          POSTGRES_PASSWORD: ci
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Integration test
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
