name: ci-process
on:
  push:
    branches:
      - develop
jobs:
  application:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Unit test
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: cd backend && npm install
      - run: cd backend && npm run unit-test
      - name: Integration test
        uses: actions/setup-node@v3
      - run: cd frontend && yarn install
