name: ci-process
on:
#  push:
#    branches:
#      - develop
  pull_request:
    branches:
      - master
jobs:
  e2e-test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [ 14.x ]
    env:
      NODE_ENV: ${{ secrets.NODE_ENV }}
      COOKIE_KEY: ${{ secrets.COOKIE_KEY }}
      COOKIE_SESSION_NAME: ${{ secrets.COOKIE_SESSION_NAME }}
      SALT: ${{ secrets.SALT }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      DO_BUCKET_NAME: ${{ secrets.DO_BUCKET_NAME }}
      DO_ACCESS_KEY: ${{ secrets.DO_ACCESS_KEY }}
      DO_SECRET_KEY: ${{ secrets.DO_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build the Postgres stack
        working-directory: e2e-tests
        run: yarn run docker:run

      - name: Install dependencies
        working-directory: e2e-tests
        run: yarn install

      - name: E2e tests
        working-directory: e2e-tests
        run: yarn run start:headless
